FROM oven/bun:1-alpine

WORKDIR /app

COPY package.json bun.lock ./
RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install

COPY . .

EXPOSE 5173

CMD ["bun", "run", "dev", "--host"]
